---

# jenkins variables
project_name: docker-mariadb
external_type: alpine_repo
release_type: stable
release_tag: latest
ls_branch: master
build_armhf: false
repo_vars:
  - BUILD_VERSION_ARG = 'MARIADB_VERSION'
  - LS_USER = 'linuxserver'
  - LS_REPO = 'docker-mariadb'
  - CONTAINER_NAME = 'mariadb'
  - DOCKERHUB_IMAGE = 'linuxserver/mariadb'
  - DEV_DOCKERHUB_IMAGE = 'lsiodev/mariadb'
  - PR_DOCKERHUB_IMAGE = 'lspipepr/mariadb'
  - DIST_IMAGE = 'alpine'
  - DIST_TAG = '3.19'
  - DIST_REPO = 'http://dl-cdn.alpinelinux.org/alpine/v3.19/main/'
  - DIST_REPO_PACKAGES = 'mariadb'
  - MULTIARCH='true'
  - CI='true'
  - CI_WEB='false'
  - CI_PORT='3306'
  - CI_SSL='false'
  - CI_DELAY='30'
  - CI_DOCKERENV='MYSQL_ROOT_PASSWORD=password'
  - CI_AUTH='user:password'
  - CI_WEBPATH=''
